# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GistLiX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GistLiX
  pod 'QRCodeReader.swift', '~> 8.0.3'
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'SwiftyJSON'
  pod 'Bond'
  pod 'Kingfisher'
  pod 'GrowingTextView'
  pod 'Locksmith'
  pod 'JVFloatLabeledTextField'

  target 'GistLiXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GistLiXUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
